# Generated by Django 4.2.16 on 2024-09-25 18:26

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default@example.com', max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(default='yourusername', max_length=30, unique=True, verbose_name='username')),
                ('password', models.CharField(default='pbkdf2_sha256$600000$5QNIunFIKWUf12YZ7YoAfn$QK004wM1GqwGVhKPHl6D850csOEjpwC5FYGasmhK8x0=', max_length=128)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_image', models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=account.models.get_profile_image_filepath)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
