# Generated by Django 4.2.16 on 2024-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$s6RspLCNFwldoCWjzq8h5K$Qj7uQg00vBk+vdx6Dl8jm/5o1Ql5Fb7J2SmlUY1HwB8=', max_length=128),
        ),
    ]
