# Generated by Django 4.2.16 on 2024-09-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_user_account_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$CsltFpQiLM98GerTdCMvBu$S2C23fEMTz3fUNxqrmnSjyDmUWFLP2Bh+7a0AFzAGts=', max_length=128),
        ),
    ]
