# Generated by Django 4.2.16 on 2024-09-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$nuC5GdY1chJ276PFLzMNRT$4gbMvUgn68uwO1oWuhmMP5xj8L09lT4GODLI97DyiFc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='username', max_length=30, unique=True, verbose_name='username'),
        ),
    ]
