# Generated by Django 4.2.16 on 2024-09-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_password_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$tNeGpMCG49JIHjEhNracyP$/4QTAXz6kSvxvWf3y3M5eVEjzJEIC6mVVm5IKW35AFs=', max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='yourusername', max_length=30, unique=True, verbose_name='username'),
        ),
    ]
