# Generated by Django 4.2.16 on 2024-09-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_password_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Zy6hXBMQ2jkJQ9EnU2W7Zi$DeolTNZisCrkzmoegkzmC+TbQ/DphjP3ZD75WTG6ifw=', max_length=128),
        ),
    ]
